/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.7/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "access-control"
include("abac")

dependencyResolutionManagement.versionCatalogs.create("libs") {
    library("jackson.jsonDatabind", "com.fasterxml.jackson.core:jackson-databind:2.17.1")
    library("spel", "org.springframework:spring-expression:6.1.8")
    library("spring.security", "org.springframework.security:spring-security-core:6.3.0")
}
